import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import ContextProvider from "./provider/ContextProvider";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Valorant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <header className="fixed top-0 left-0 w-full z-50">
            <Navbar />
          </header>
          <div className="mt-[70px]">
            {children}
          </div>
        </ContextProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
