import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import AppProvider from "../components/Provider/AppProvider";
import MainWrapper from "../components/Wrapper/MainWrapper";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: '400',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Valorant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${anton.variable} ${geistMono.variable} antialiased`}
      >
          <AppProvider>
            <MainWrapper>
              <header>
                <Navbar />
              </header>
              {children}
              <Footer />
            </MainWrapper>
          </AppProvider>
      </body>
    </html>
  );
}
